[versions]
plugin-version = "1.0.0"

runtask-version = "2.3.1"

[libraries]
async-profiler = { group = "tools.profiler", name = "async-profiler", version = "4.0"}
guava = { group = "com.google.guava", name = "guava", version = "33.4.8-jre" }

## Paper
paper-api = { group = "io.papermc.paper", name = "paper-api", version = "1.17-R0.1-SNAPSHOT" }

[plugins]
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask-version" }
shadow = { id = "com.gradleup.shadow", version = "9.0.0-beta13" }